namespace Infra.Core.Enums
{
    public enum ConditionSymbol
    {
        Contains,
        Contain,
        ContainAll,
        NotContain,
        NotContainAll,
        Equal,
        Equals,
        NotEqual,
        NotEquals,
        Greater,
        GreaterEqual,
        GreaterEqualOrNone,
        Less,
        LessEqual,
        In,
        NotIn,
        Between,
        NotMapped,
        LeftOrRight,
        None,
        Not,
        CountGreaterEqual,
        CountEqual,
    }
}
